  
# This is a basic workflow to help you get started with Actions

name: Deploy Website Changes

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        
      - name: Install NodeJS
        uses: actions/setup-node@v2-beta
        with: 
          node-version: 12
        
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install

      - name: Build React App
        run: yarn build
        
      - name: Install Surge    
        run: npm install --global surge
        
      - name: Deploy React App to Surge
        run:  surge ./build expense-tracker-ikram.surge.sh --token ${{ secrets.SURGE_TOKEN }}
